---
title: "waning_analysis_ba"
author: "Tanmayi Patharkar"
date: "`r Sys.Date()`"
output: html_document
---

#Load Data
```{r}
data <- read.csv("./data/data_03102025.csv") 
dict <- read_excel("./data/dict.xlsx")

data <- data %>%
  mutate(posrat_p1_date = as.Date(posrat_p1_date, format = "%Y-%m-%d")) %>%
  mutate(across(contains("date"), \(x) as.Date(x, format = "%Y-%m-%d"))) 
```

#Load Vaccine Dosages 
```{r}
data <- data %>%
  mutate(
    one_dose_permutation = paste(dose1_brand),
    two_dose_permutation = paste(dose1_brand, dose2_brand, sep = "-"),
    three_dose_permutation = paste(dose1_brand, dose2_brand, dose3_brand, sep = "-"),
    four_dose_permutation = paste(dose1_brand, dose2_brand, dose3_brand, dose4_brand, sep = "-"),
    five_dose_permutation = paste(dose1_brand, dose2_brand, dose3_brand, dose4_brand, dose5_brand, sep = "-")
  )

#Make separate data frames for each vaccine permutation
one_dose_data <- data %>%
  filter(!grepl("NA", one_dose_permutation))

two_dose_data <- data %>%
  filter(!grepl("NA", two_dose_permutation))

three_dose_data <- data %>%
  filter(!grepl("NA", three_dose_permutation))

four_dose_data <- data %>%
  filter(!grepl("NA", four_dose_permutation))

five_dose_data <- data %>%
  filter(!grepl("NA", five_dose_permutation))
```

#Permutation Counts
```{r}
one_permutation_count <- one_dose_data %>%
  group_by(one_dose_permutation) %>% 
  summarise(count = n(), .groups = 'drop')

two_permutation_count <- two_dose_data %>%
  group_by(two_dose_permutation) %>% 
  summarise(count = n(), .groups = 'drop')

three_permutation_count <- three_dose_data %>%
  group_by(three_dose_permutation) %>% 
  summarise(count = n(), .groups = 'drop')

four_permutation_count <- four_dose_data %>%
  group_by(four_dose_permutation) %>% 
  summarise(count = n(), .groups = 'drop')

five_permutation_count <- five_dose_data %>%
  group_by(five_dose_permutation) %>% 
  summarise(count = n(), .groups = 'drop')
```


#Antibody Value Measurements
```{r}
source("scripts/fc_vaccine_perm.R")
```

#SVNT_BA5

#DOSE FOUR 
```{r}
four_svnt_ba5 <- fc_perm_summary(four_dose_data, four_dose_permutation, v4_svnt_ba5, min_n = 5, dose_label = "4 Dose")

four_valid_perms      <- four_svnt_ba5$valid_perms
one_dose_medians     <- four_svnt_ba5$medians
one_n_levels         <- four_svnt_ba5$n_levels
one_mid_x            <- four_svnt_ba5$mid_x

print(four_svnt_ba5$valid_perm_count)
```

