---
title: "wt_time_analysis"
author: "Tanmayi Patharkar"
date: "`r Sys.Date()`"
output: html_document
---
#load packages 
```{r}
library(librarian)
shelf(dplyr) 
shelf(tidyverse)
shelf(readxl)
shelf(tidyr)
shelf(rlang)
shelf(patchwork)
```

#data loading and processig 
```{r}
data <- read.csv("./data/data_03102025.csv") 
dict <- read_excel("./data/dict.xlsx")

data <- data %>%
  mutate(posrat_p1_date = as.Date(posrat_p1_date, format = "%Y-%m-%d")) %>%
  mutate(across(contains("date"), \(x) as.Date(x, format = "%Y-%m-%d"))) 
```


#Baseline Value Measurements
```{r}
source("scripts/fc_get_baselines.R")
```

```{r}
baseline_elisa <- get_baselines(data, "elisa_wt")  
baseline_svnt <- get_baselines(data, "svnt_wt")    

print(head(baseline_elisa))
print(head(baseline_svnt))
```

##ELISA PER DOSE 

#TWO DOSES 

```{r}
two_dose_data$base_elisa <- baseline_elisa$baseline_value[match(two_dose_data$id, baseline_elisa$id)]

two_dose_elisa_homologous <- two_dose_data %>%
  filter(!is.na(base_elisa) & !is.na(v1_elisa_wt) & !is.na(v2_elisa_wt)) %>%
  filter(grepl("1-1|4-4", two_dose_permutation))

shade_df <- tibble(
  xmin = c(0.5, 1.5, 2.5),
  xmax = c(1.5, 2.5, 3.5),
  alpha = c(0.02, 0.05, 0.08)
)
```


```{r}
two_dose_long_elisa <- two_dose_elisa_homologous %>%
  select(id, base_elisa, v1_elisa_wt, v2_elisa_wt, two_dose_permutation) %>%
  pivot_longer(cols = c(base_elisa, v1_elisa_wt, v2_elisa_wt),
               names_to = "dose", values_to = "value") %>%
  mutate(
    color = ifelse(two_dose_permutation == "1-1", "#1F77B4", "#FF7F0E"),
    dose = factor(dose, levels = c("base_elisa", "v1_elisa_wt", "v2_elisa_wt"))
  )

median_values_elisa <- two_dose_long_elisa %>%
  group_by(dose, two_dose_permutation) %>%
  summarize(median_value = median(value, na.rm = TRUE), .groups = "drop")
```


```{r}
elisa_wt_time_plot_2_counts <- two_dose_elisa_homologous %>%
  group_by(two_dose_permutation) %>%
  summarise(n = n_distinct(id), .groups = "drop")

print(elisa_wt_time_plot_2_counts)

elisa_wt_time_plot_2_counts <- with(elisa_wt_time_plot_2_counts, 
                   paste("B: n =", n[two_dose_permutation == "1-1"], "\n",
                         "S: n =", n[two_dose_permutation == "4-4"]))

shade_df <- tibble(
  xmin = c(0.5, 1.5, 2.5),
  xmax = c(1.5, 2.5, 3.5),
  alpha = c(0.02, 0.05, 0.08)
)

elisa_wt_time_plot_2 <- ggplot() +
  geom_rect(
    data = shade_df,
    aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, alpha = alpha),
    fill = "gray40", inherit.aes = FALSE, show.legend = FALSE
  ) +
  scale_alpha_identity() +
  geom_line(
    data = two_dose_long_elisa,
    aes(x = dose, y = value, group = id, color = two_dose_permutation),
    alpha = 0.25, size = 0.4, show.legend = FALSE
  ) +
  geom_point(
    data = two_dose_long_elisa,
    aes(x = dose, y = value, color = two_dose_permutation),
    alpha = 0.25, size = 0.8, show.legend = FALSE
  ) +
  geom_line(
    data = median_values_elisa,
    aes(x = dose, y = median_value, group = two_dose_permutation, color = two_dose_permutation),
    size = 1.4
  ) +
  geom_point(
    data = median_values_elisa,
    aes(x = dose, y = median_value, color = two_dose_permutation),
    size = 3
  ) +
  scale_color_manual(values = c("1-1" = "#1F77B4", "4-4" = "#FF7F0E")) +
  scale_x_discrete(labels = c("base_elisa" = "Baseline",
                              "v1_elisa_wt" = "Dose 1",
                              "v2_elisa_wt" = "Dose 2")) +
  scale_y_continuous(limits = c(0, 6), expand = c(0, 0)) +
  labs(x = NULL,
       y = "WT RBD ELISA (OD value)") +
  theme_minimal() +
   theme(plot.caption = element_text(face = "bold", size = 14, hjust = 0.5),
        plot.title = element_text(face = "bold", size = 14),
        axis.title = element_text(face = "bold"),
        axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face = "bold"),  
        panel.grid.major = element_blank(),  
        panel.grid.minor = element_blank(),  
        axis.ticks = element_line(),  
        legend.position = "none",
        panel.border = element_blank(),
        axis.line = element_line(size = 0.5, color = "black", linetype = "solid")
  ) +
  geom_label(
    aes(x = 0.5, y = 5.8, label = elisa_wt_time_plot_2_counts),
    hjust = 0,  # Left-align
    vjust = 1,  # Top-align
    size = 3, 
    fontface = "bold",  
    color = "black",
    fill = "white",  
    label.padding = unit(0.3, "lines"),  
    label.r = unit(0.15, "lines"),  
    label.size = 0.3, 
    family = "sans"  
  )

elisa_wt_time_plot_2

#ggsave("elisa_wt_time_plot.pdf", plot = elisa_wt_time_plot, width = 10, height = 6)
```

##THREE DOSES 
```{r}
three_dose_data$base_elisa <- baseline_elisa$baseline_value[match(three_dose_data$id, baseline_elisa$id)]

three_dose_elisa_homologous <- three_dose_data %>%
filter(!is.na(base_elisa) & !is.na(v1_elisa_wt) & !is.na(v2_elisa_wt) & !is.na(v3_elisa_wt)) %>%
filter(grepl("1-1-1|4-4-4", three_dose_permutation))

three_dose_elisa_homologous
```


```{r}
three_dose_long <- three_dose_elisa_homologous %>%
  select(id, base_elisa, v1_elisa_wt, v2_elisa_wt, v3_elisa_wt, three_dose_permutation) %>%
  pivot_longer(cols = c(base_elisa, v1_elisa_wt, v2_elisa_wt, v3_elisa_wt), 
               names_to = "dose", values_to = "value")

three_dose_long <- three_dose_long %>%
  mutate(color = ifelse(three_dose_permutation == "1-1-1", "#1F77B4", "#FF7F0E")) 

median_values <- three_dose_long %>%
  group_by(dose, three_dose_permutation) %>%
  summarize(median_value = median(value, na.rm = TRUE), .groups = 'drop')
```


```{r}
elisa_wt_time_plot_3_sample_counts <- three_dose_elisa_homologous %>%
  group_by(three_dose_permutation) %>%
  summarise(n = n_distinct(id), .groups = "drop")

print(elisa_wt_time_plot_3_sample_counts)

elisa_wt_time_plot_3_sample_counts <- with(elisa_wt_time_plot_3_sample_counts, 
                   paste("B: n =", n[three_dose_permutation == "1-1-1"], "\n",
                         "S: n =", n[three_dose_permutation == "4-4-4"]))

shade_df <- tibble(
  xmin = c(0.5, 1.5, 2.5),
  xmax = c(1.5, 2.5, 3.5),
  alpha = c(0.02, 0.05, 0.08)
)

elisa_wt_time_plot_3 <- ggplot() +
  geom_rect(
    data = shade_df,
    aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, alpha = alpha),
    fill = "gray40", inherit.aes = FALSE, show.legend = FALSE
  ) +
  scale_alpha_identity() +
  geom_line(
    data = three_dose_long,
    aes(x = dose, y = value, group = id, color = three_dose_permutation),
    alpha = 0.25, size = 0.4, show.legend = FALSE
  ) +
  geom_point(
    data = three_dose_long,
    aes(x = dose, y = value, color = three_dose_permutation),
    alpha = 0.25, size = 0.8, show.legend = FALSE
  ) +
  geom_line(
    data = median_values,
    aes(x = dose, y = median_value, group = three_dose_permutation, color = three_dose_permutation),
    size = 1.4
  ) +
  geom_point(
    data = median_values,
    aes(x = dose, y = median_value, color = three_dose_permutation),
    size = 3) + 
  scale_color_manual(name = "Vaccine Type", values = c("1-1-1" = "#1F77B4", "4-4-4" = "#FF7F0E"), labels = c("1-1-1" = "B", "4-4-4" = "S")) +
  scale_x_discrete(labels = c("base_elisa" = "Baseline",
                              "v1_elisa_wt" = "Dose 1",
                              "v2_elisa_wt" = "Dose 2",
                              "v3_elisa_wt" = "Dose 3")) +
  scale_y_continuous(limits = c(0, 6), expand = c(0, 0)) +
  labs(x = NULL,
       y = "WT RBD ELISA (OD value)") +
  theme_minimal() +
   theme(
    plot.caption = element_text(face = "bold", size = 14, hjust = 0.5),
    plot.title = element_text(face = "bold", size = 14),
    axis.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks = element_line(),
    panel.border = element_blank(),
    axis.line = element_line(size = 0.5, color = "black", linetype = "solid"),
    legend.position = c(0.98, 0.98),  # Top-right corner
    legend.justification = c("right", "top"),  # Anchor legend to top-right
    legend.background = element_rect(fill = "white", color = "black", size = 0.5),  # White background with border
    legend.margin = margin(6, 6, 6, 6), 
    legend.title = element_text(face = "bold", size = 10), 
    legend.text = element_text(size = 8),  
    legend.key.size = unit(0.4, "cm"),  # Smaller legend keys for a compact look
    legend.key = element_rect(fill = "white", color = "transparent")
  ) +
  geom_label(
    aes(x = 0.5, y = 5.8, label = elisa_wt_time_plot_3_sample_counts),
    hjust = 0,  # Left-align
    vjust = 1,  # Top-align
    size = 3, 
    fontface = "bold",  
    color = "black",
    fill = "white",  
    label.padding = unit(0.3, "lines"),  
    label.r = unit(0.15, "lines"),  
    label.size = 0.3, 
    family = "sans"  
  )

elisa_wt_time_plot_3

ggsave("elisa_wt_time_plot_3.pdf", plot = elisa_wt_time_plot_3, width = 10, height = 6)
```


#SVNT 

##TWO DOSE 
```{r}
two_dose_data$base_svnt <- baseline_svnt$baseline_value[match(two_dose_data$id, baseline_svnt$id)]

two_dose_svnt_homologous <- two_dose_data %>%
  filter(!is.na(base_svnt) & !is.na(v1_svnt_wt) & !is.na(v2_svnt_wt)) %>%
  filter(grepl("1-1|4-4", two_dose_permutation))

shade_df <- tibble(
  xmin = c(0.5, 1.5, 2.5),
  xmax = c(1.5, 2.5, 3.5),
  alpha = c(0.02, 0.05, 0.08)
)

two_dose_long_svnt <- two_dose_svnt_homologous %>%
  select(id, base_svnt, v1_svnt_wt, v2_svnt_wt, two_dose_permutation) %>%
  pivot_longer(cols = c(base_svnt, v1_svnt_wt, v2_svnt_wt),
               names_to = "dose", values_to = "value") %>%
  mutate(
    color = ifelse(two_dose_permutation == "1-1", "#1F77B4", "#FF7F0E"),
    dose = factor(dose, levels = c("base_svnt", "v1_svnt_wt", "v2_svnt_wt"))
  )

median_values_svnt <- two_dose_long_svnt %>%
  group_by(dose, two_dose_permutation) %>%
  summarize(median_value = median(value, na.rm = TRUE), .groups = "drop")

```

```{r}
svnt_wt_time_plot_sample_counts <- two_dose_svnt_homologous %>%
  group_by(two_dose_permutation) %>%
  summarise(n = n_distinct(id), .groups = "drop")

print(svnt_wt_time_plot_sample_counts)

svnt_wt_time_plot_sample_counts <- with(svnt_wt_time_plot_sample_counts, 
                   paste("B: n =", n[two_dose_permutation == "1-1"], "\n",
                         "S: n =", n[two_dose_permutation == "4-4"]))


svnt_wt_time_plot <- ggplot() +
  geom_rect(
    data = shade_df,
    aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, alpha = alpha),
    fill = "gray40", inherit.aes = FALSE, show.legend = FALSE
  ) +
  scale_alpha_identity() +
  geom_line(
    data = two_dose_long_svnt,
    aes(x = dose, y = value, group = id, color = two_dose_permutation),
    alpha = 0.25, size = 0.4, show.legend = FALSE
  ) +
  geom_point(
    data = two_dose_long_svnt,
    aes(x = dose, y = value, color = two_dose_permutation),
    alpha = 0.25, size = 0.8, show.legend = FALSE
  ) +
  geom_line(
    data = median_values_svnt,
    aes(x = dose, y = median_value, group = two_dose_permutation, color = two_dose_permutation),
    size = 1.4
  ) +
  geom_point(
    data = median_values_svnt,
    aes(x = dose, y = median_value, color = two_dose_permutation),
    size = 3
  ) +
  scale_color_manual(values = c("1-1" = "#1F77B4", "4-4" = "#FF7F0E")) +
  scale_x_discrete(labels = c("base_svnt" = "Baseline",
                              "v1_svnt_wt" = "Dose 1",
                              "v2_svnt_wt" = "Dose 2")) +
  scale_y_continuous(limits = c(0, 110), breaks = seq(0, 100, by = 20)) +
  labs(x = NULL, y = "WT sVNT Inhibition (%)") +
  theme_minimal() +
  theme(
    plot.caption = element_text(face = "bold", size = 14, hjust = 0.5),
    plot.title = element_text(face = "bold", size = 14),
    axis.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks = element_line(),
    legend.position = "none",
    panel.border = element_blank(),
    axis.line = element_line(size = 0.5, color = "black", linetype = "solid")
  ) +
  geom_label(
    aes(x = 0.5, y = 105, label = svnt_wt_time_plot_sample_counts),
    hjust = 0,  # Left-align
    vjust = 1,  # Top-align
    size = 3, 
    fontface = "bold",  
    color = "black",
    fill = "white",  
    label.padding = unit(0.3, "lines"),  
    label.r = unit(0.15, "lines"),  
    label.size = 0.3, 
    family = "sans"  
  )

svnt_wt_time_plot

ggsave("svnt_wt_time_plot.pdf", plot = svnt_wt_time_plot, width = 10, height = 6)
```

##THREE DOSE

```{r}
three_dose_data$base_svnt <- baseline_svnt$baseline_value[match(three_dose_data$id, baseline_svnt$id)]

three_dose_svnt_homologous <- three_dose_data %>%
  filter(!is.na(base_svnt) & !is.na(v1_svnt_wt) & !is.na(v2_svnt_wt) & !is.na(v3_svnt_wt)) %>%
  filter(grepl("1-1-1|4-4-4", three_dose_permutation))

shade_df <- tibble(
  xmin = c(0.5, 1.5, 2.5, 3.5),
  xmax = c(1.5, 2.5, 3.5, 4.5),
  alpha = c(0.02, 0.05, 0.08, 0.11)
)

three_dose_long_svnt <- three_dose_svnt_homologous %>%
  select(id, base_svnt, v1_svnt_wt, v2_svnt_wt, v3_svnt_wt, three_dose_permutation) %>%
  pivot_longer(cols = c(base_svnt, v1_svnt_wt, v2_svnt_wt, v3_svnt_wt),
               names_to = "dose", values_to = "value") %>%
  mutate(
    color = ifelse(three_dose_permutation == "1-1-1", "#1F77B4", "#FF7F0E"),
    dose = factor(dose, levels = c("base_svnt", "v1_svnt_wt", "v2_svnt_wt", "v3_svnt_wt"))
  )

median_values_svnt <- three_dose_long_svnt %>%
  group_by(dose, three_dose_permutation) %>%
  summarize(median_value = median(value, na.rm = TRUE), .groups = "drop")

```


```{r}
svnt_wt_time_plot_3_sample_counts <- three_dose_svnt_homologous %>%
  group_by(three_dose_permutation) %>%
  summarise(n = n_distinct(id), .groups = "drop")

print(svnt_wt_time_plot_3_sample_counts)

svnt_wt_time_plot_3_sample_counts <- with(svnt_wt_time_plot_3_sample_counts, 
                   paste("B: n =", n[three_dose_permutation == "1-1-1"], "\n",
                         "S: n =", n[three_dose_permutation == "4-4-4"]))

svnt_wt_time_plot_3 <- ggplot() +
  geom_rect(
    data = shade_df,
    aes(xmin = xmin, xmax = xmax, ymin = -Inf, ymax = Inf, alpha = alpha),
    fill = "gray40", inherit.aes = FALSE, show.legend = FALSE
  ) +
  scale_alpha_identity() +
  geom_line(
    data = three_dose_long_svnt,
    aes(x = dose, 
        y = ifelse(dose == "base_svnt", pmax(0, value), value), 
        group = id, 
        color = three_dose_permutation),
    alpha = 0.25, size = 0.4, show.legend = FALSE
  ) +
  geom_point(
    data = three_dose_long_svnt,
    aes(x = dose, 
        y = ifelse(dose == "base_svnt", pmax(0, value), value), 
        color = three_dose_permutation),
    alpha = 0.25, size = 0.8, show.legend = FALSE
  ) +
  geom_line(
    data = median_values_svnt,
    aes(x = dose, 
        y = ifelse(dose == "base_svnt", pmax(0, median_value), median_value), 
        group = three_dose_permutation, 
        color = three_dose_permutation),
    size = 1.4
  ) +
  geom_point(
    data = median_values_svnt,
    aes(x = dose, 
        y = ifelse(dose == "base_svnt", pmax(0, median_value), median_value), 
        color = three_dose_permutation),
    size = 3
  ) +
  scale_color_manual(values = c("1-1-1" = "#1F77B4", "4-4-4" = "#FF7F0E")) +
  scale_x_discrete(labels = c("base_svnt" = "Baseline",
                              "v1_svnt_wt" = "Dose 1",
                              "v2_svnt_wt" = "Dose 2",
                              "v3_svnt_wt" = "Dose 3")) +
  scale_y_continuous(limits = c(0, 110), breaks = seq(0, 100, by = 20)) +
  labs(x = NULL, y = "WT sVNT Inhibition (%)") +
  theme_minimal() +
  theme(
    plot.caption = element_text(face = "bold", size = 14, hjust = 0.5),
    plot.title = element_text(face = "bold", size = 14),
    axis.title = element_text(face = "bold"),
    axis.text.x = element_text(angle = 0, hjust = 0.5, vjust = 0.5, face = "bold"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks = element_line(),
    legend.position = "none",
    panel.border = element_blank(),
    axis.line = element_line(size = 0.5, color = "black", linetype = "solid")
  ) +
  geom_label(
    aes(x = 0.5, y = 105, label = svnt_wt_time_plot_3_sample_counts),
    hjust = 0,  # Left-align
    vjust = 1,  # Top-align
    size = 3, 
    fontface = "bold",  
    color = "black",
    fill = "white",  
    label.padding = unit(0.3, "lines"),  
    label.r = unit(0.15, "lines"),  
    label.size = 0.3, 
    family = "sans"  
  )

svnt_wt_time_plot_3
```

##MAKING PANELS 

```{r}
time_analysis_combined_plot <- (elisa_wt_time_plot_2 + elisa_wt_time_plot_3 + 
                         svnt_wt_time_plot + 
                         svnt_wt_time_plot_3) +
  plot_layout(ncol = 2) + 
  plot_annotation(title = "WT Analysis per Dosage ", 
                  theme = theme(plot.title = element_text(face = "bold", size = 16, hjust = 0.5))) + 
  theme(plot.background = element_blank(),
        panel.border = element_blank(),    
        plot.margin = margin(0, 0, 0, 0))

print(time_analysis_combined_plot)

ggsave("time_analysis_combined_plot.pdf", plot = time_analysis_combined_plot, width = 10, height = 6)
```

